version: '3.8'

services:
  # Service for Apple Silicon (M1/M2/M3) chips
  app-silicon:
    build:
      context: .
      dockerfile: Dockerfile.silicon
    ports:
      - "8080:8080"
      - "8082:8082"  # H2 console port
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
    volumes:
      - ~/.m2:/root/.m2

  # Service for Intel/AMD processors
  app-amd64:
    build:
      context: .
      dockerfile: Dockerfile.amd64
    ports:
      - "8080:8080"
      - "8082:8082"  # H2 console port
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
    volumes:
      - ~/.m2:/root/.m2 