---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAIgT3LZw1DubfalJBxVffcJcGiIy7BGDO0cVdtAGbCYECUmc4X/VUVJ+BpSNeBGEABXBI6jylZzR5UPPZxMl3gW8vG/4hL1yezOHT1mtBfC7dFVnU1aq6GnLRA63aSzvzwJwhNy/uj1b1KUK8ripk9TrrqPl2bciuddcie0XqGhriUFodKxktq4Iwi07lfZuJCBvPF41imyGY+p5U0aGlZkor1RJryr3uk/VKXKWcpe2YM+W3aTOV7Omw/3UdFPl6J0vINsMfCJ5ox/k3lUIN99g0QPMiP4qPacCAES34yz8RIt0R07FL7qDNVG4g5QgqF+n8Fkhs2ZquY3wWMvYEx8KEi2NWCoTvkixbl2Ypn5Ngy430eFtsRd0fl9CfhI+V9cUc/N/Grld4/U4YG2O24EWkjZfXKdnBVjDhX26wd2QpBEKtcpeMwyFwrS4jy1NSucrPAWBSmV3x+B8sIaRlkpB5OQOoUd+87qOXv6yqea3Yvk+45KZlD4K1m73fW26zuWu6UBl8JBSy3cxl4m6qdXVeJsm/yV/1k0+DBgTcySD9Gv5vk8lZTeVu6Qz0rWJY5LClm+tVehd6YTky8qSe+hlxk2z+X+NK4geUkUmz+5zq866JIuPZ1nBKQmIvhLBKadSSLs/tqWtuDh4QGJyl1s/q/X80BbWyfvd1vprx5IFubYkXBj90z2pkzS+gBcuKNud8cXy1aylCcsHyKqAA+w5ECcoFQ9cI=
    admin-user: AgBIMnv5fpo0nkHgD89niVXqLCeLTL1tg43Qcve7w5R7kKqWlB/XeSsv0uVGLGuCCPeSe/jTcjY6JQU4DHE0Zzi7GKlwfJk3QtheGCmR/3nL4vtLvcVfPBMeNEhAkxWFJr4K893wH76U5sI7a76lwotoL6W34XAyxN5/uOOxSBa9EtsO++b2hEaThTSEb60Gd7lsf2gwUqqo8QZ9hiqZu9SNC4kbE4nbqRQiYor0j+be8RISHoPTJKr33Z6vuqK3TYHdHdJvSGvDRtqIjN+Z1Az7GK5bnovp8DjZjnpqPzKAbMtKvxcF0ZK1MhuACao90AViPJEUVA7uOZyP9S+xLiyIEoH7kHPPFYuXvK2SKJkU8MQij2AKtr2EplST8/N26vJfO3hmNY+YGk1wJw5rKiFQxDByVF5XU8EfKgX4FA+GGsB/terduCURMmknil2meiviLFoL8pUIlur6VooqTLfOK3OQxvHjWdIaB53uB5J6WE2dczw2V4aWXU9NjFK7JQkLq4cL+BFhN6/6XdF6YtfxYNO3NQsJTmDV3Ra0TEso5rWaiuViSKSj8HmsapNX6F6CxJM3S58BEMLyuOhGcIN0gNQoj88sWKKD7EocjTaXgxoI6YwViAKT3IoRhuvqYPui1z07Sk7KAbCnyIt67Uu0FF4i7MMRR/KVX5jUp32rkmvixfcCWwk20BJN6d6iQVGBE0j+Xg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
