#!/usr/bin/env python3
"""Generate the Argo CD Applications in deploy/argocd/apps from deploy/platform/components.tsv.

    python3 scripts/gen-argocd-apps.py           # write the files
    python3 scripts/gen-argocd-apps.py --check   # CI: fail if the committed files are stale

One table drives both Argo CD (GitOps) and scripts/cluster-up.sh --mode=direct, so the two
can never install different versions or values. Standard library only.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TABLE = ROOT / "deploy/platform/components.tsv"
OUT = ROOT / "deploy/argocd/apps"
SELF_REPO = "https://github.com/itsdamian/cube_test.git"
SELF_REVISION = "main"
HEADER = "# GENERATED by scripts/gen-argocd-apps.py from deploy/platform/components.tsv - do not edit.\n"


def rows():
    for line in TABLE.read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.startswith("#"):
            cols = line.split("\t")
            if len(cols) != 9:
                sys.exit(f"components.tsv: expected 9 tab-separated columns, got {len(cols)}: {line!r}")
            yield dict(zip(["name", "namespace", "wave", "type", "source", "ref", "path", "values", "options"], cols))


def application(c):
    opts = set() if c["options"] == "-" else set(c["options"].split(","))
    repo = SELF_REPO if c["source"] == "self" else c["source"]
    revision = SELF_REVISION if c["source"] == "self" else c["ref"]
    lines = [
        HEADER,
        "apiVersion: argoproj.io/v1alpha1",
        "kind: Application",
        "metadata:",
        f"  name: {c['name']}",
        "  namespace: argocd",
        "  annotations:",
        f'    argocd.argoproj.io/sync-wave: "{c["wave"]}"',
    ]
    if "nofinalizer" not in opts:
        # Deleting the Application also deletes what it deployed.
        lines += ["  finalizers:", "    - resources-finalizer.argocd.argoproj.io"]
    lines += [
        "spec:",
        "  project: default",
    ]
    if c["type"] == "helm":
        lines += [
            "  sources:",
            f"    - repoURL: {repo}",
            f"      chart: {c['path']}",
            f"      targetRevision: {revision}",
            "      helm:",
            f"        releaseName: {c['name']}",
            "        valueFiles:",
            f"          - $values/deploy/platform/values/{c['values']}",
            f"    - repoURL: {SELF_REPO}",
            f"      targetRevision: {SELF_REVISION}",
            "      ref: values",
        ]
    else:
        lines += [
            "  source:",
            f"    repoURL: {repo}",
            f"    targetRevision: {revision}",
            f"    path: {c['path']}",
        ]
    lines += ["  destination:", "    server: https://kubernetes.default.svc"]
    if c["namespace"] != "-":
        lines.append(f"    namespace: {c['namespace']}")
    lines += ["  syncPolicy:"]
    if "manual" not in opts:
        lines += [
            "    automated:",
            f"      prune: {'false' if 'noprune' in opts else 'true'}",
            f"      selfHeal: {'false' if 'noselfheal' in opts else 'true'}",
        ]
    sync_options = ["CreateNamespace=true"]
    if "ssa" in opts:
        sync_options.append("ServerSideApply=true")
    lines += ["    syncOptions:"] + [f"      - {o}" for o in sync_options]
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv
    wanted = {f"{c['name']}.yaml": application(c) for c in rows()}
    if check:
        existing = {p.name: p.read_text(encoding="utf-8") for p in OUT.glob("*.yaml")}
        if existing != wanted:
            stale = sorted(set(existing) ^ set(wanted) | {k for k in wanted if existing.get(k) != wanted[k]})
            sys.exit("deploy/argocd/apps is out of date (run scripts/gen-argocd-apps.py): " + ", ".join(stale))
        print(f"deploy/argocd/apps up to date ({len(wanted)} applications)")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.yaml"):
        if old.name not in wanted:
            old.unlink()
    for name, text in wanted.items():
        (OUT / name).write_text(text, encoding="utf-8")
    print(f"wrote {len(wanted)} applications to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
